FROM ubuntu:16.04
# docker build -t vanessa/ubuntu-dependencies:16.04 .
RUN apt-get update && \
    apt-get install -y python
ADD . /
RUN chmod u+x entrypoint.sh && \
    chmod u+x apt-cache.py
ENTRYPOINT ["/entrypoint.sh"]
